apiVersion: v1
kind: Service
metadata:
  name: gateways-service
spec:
  type: LoadBalancer
  selector:
    app: gateways
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000

---

apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  type: LoadBalancer
  selector:
    app: authenticationAPI
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000