apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  selector:
    matchLabels:
      app: authenticationAPI
  template:
    metadata:
      labels:
        app: authenticationAPI
    spec:
      containers:
      - name: authentication-api-container
        image: noahkoole/gymshare-authentication
        env:
          - name: Audience
            value: "gymshare-1e65f"
          - name: Issuer
            value: "https://securetoken.google.com/gymshare-1e65f"
          - name: FirebaseAPIKey
            value: AIzaSyBhm7syHZDCfPGG7pTSliONjvxckzzOz1c
        imagePullPolicy: Always
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: authentication
spec:
  type: ClusterIP
  selector:
    app: authenticationAPI
  ports:
  - port: 8080
    targetPort: 80