apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateways-deployment
spec:
  selector:
    matchLabels:
      app: gateways
  template:
    metadata:
      labels:
        app: gateways
    spec:
      containers:
      - name: gateways-container
        image: noahkoole/gateways
        env:
          - name: Audience
            value: "gymshare-1e65f"
          - name: Issuer
            value: "https://securetoken.google.com/gymshare-1e65f"
          - name: ENVIRONMENT
            value: prod
        imagePullPolicy: Always
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
spec:
  selector:
    matchLabels:
      app: authenticationAPI
  template:
    metadata:
      labels:
        app: authenticationAPI
    spec:
      containers:
      - name: authentication-api-container
        image: noahkoole/backendauthenticationserver
        env:
          - name: Audience
            value: "gymshare-1e65f"
          - name: Issuer
            value: "https://securetoken.google.com/gymshare-1e65f"
          - name: FirebaseAPIKey
            value: AIzaSyBhm7syHZDCfPGG7pTSliONjvxckzzOz1c
        imagePullPolicy: Always
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 80