apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-users
spec:
  selector:
    matchLabels:
      app: mysql-users
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-users
    spec:
      containers:
      - image: mysql:latest
        name: mysql-users
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: gymshare_users
        ports:
        - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-users
spec:
  type: ClusterIP
  ports:
  - port: 3306
  selector:
    app: mysql-users